platform :ios, '13'

use_frameworks!
inhibit_all_warnings!

def shared_pods
#  pod 'FolioReaderKit'
  pod 'FolioReaderKit', :git => 'https://github.com/oafinalboy/FolioReaderKit.git', :branch => 'oadev'
end

def testing_pods
  pod 'Quick', '1.3.2'
  pod 'Nimble', '7.3.1' 
end

target 'Example' do
  shared_pods
end

target 'Storyboard-Example' do
    shared_pods
end

target 'MultipleInstance-Example' do
    shared_pods
end

target 'FolioReaderTests' do
  shared_pods
  testing_pods
end

#post_install do |installer|
#  installer.pods_project.build_configurations.each do |config|
#    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
#  end
#end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        end
    end
end
